class NodeData:
    DEPTH = 'depth'
    STATE = 'state'
    ACTION = 'action'
    REWARD = 'reward'
    VISIT = 'visit' 
    VALUE = 'value'
    VALUE_HISTORY = 'value_history'
    Trajectory = 'trajectory'
    NUMBER = 'number'
    TYPE = 'type'
    GOAL = 'goal'