class NodeData:
    DEPTH = 'depth'
    STATE = 'state'
    ACTION = 'action'
    REWARD = 'reward'
    VISITS = 'visits' 
    Q = 'q'
    Q_HISTORY = 'q_history'
    Trajectory = 'trajectory'
    NUMBER = 'number'
    TYPE = 'type'